server:
  port: 8090
spring:
  application:
    name: fdProvider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
ribbon:
  eager-load:
    clients: fdCustomer
    enabled: true
logging:
  level:
    cloud.exerices.fd: debug
dubbo:
  protocol:
    port: -1
    name: dubbo