server:
  port: 8081
spring:
  application:
    name: sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
#        port: 8719   sentinel默认启动一个端口为8719,这个端口的作用是用户在sentinel的 dashboard上操作时通过此端口传递到项目中

#Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
