
dubbo:
  protocol:
    name: dubbo
    port: -1
spring:
  application:
    name: customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8082
        port: 8728
server:
  port: 8080
