server:
  port: 8085
dubbo:
  cloud:
    subscribed-services: customer
  protocol:
    name: dubbo
    port: -1
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848